handle errors

diff --git a/.github/workflows/clean.yaml b/.github/workflows/clean.yaml
--- a/.github/workflows/clean.yaml
+++ b/.github/workflows/clean.yaml
@@ -39,13 +39,13 @@ jobs:
 
           vercel_output=$(vercel remove ${{ env.VERCEL_PROJECT_NAME }} --safe --yes --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
           exit_code=$?
-          echo "$vercel_output" | tee out.txt
+          echo "$vercel_output" | tee vercel_out.txt
 
           if [ $exit_code -ne 0 ]; then
-              echo "Vercel command failed with exit code $exit_code"
+              echo "vercel command failed with exit code $exit_code"
           fi
 
-          if grep -q "Could not find unaliased deployments" out.txt; then
+          if grep -q "Could not find unaliased deployments" vercel_out.txt; then
               echo "No unaliased deployment found, skipping error"
               exit_code=0
           fi
@@ -70,11 +70,32 @@ jobs:
           workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_ID_PROVIDER }}
           service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
 
-      - uses: google-github-actions/setup-gcloud@v1
+      - name: Setup gcloud CLI
+        uses: google-github-actions/setup-gcloud@v1
         with:
           version: '>= 363.0.0'
           project_id: blazing-fire-reports
 
       - name: "Delete the report at: 'blazing-fire-playwright-reports/pr-${{ github.event.pull_request.number }}'"
-        run: gcloud storage rm --recursive gs://blazing-fire-playwright-reports/pr-${{ github.event.pull_request.number }}/
-        # what happened if the folder has been deleted already?
+        run: gcloud storage rm --recursive --continue-on-error gs://blazing-fire-playwright-reports/pr-${{ github.event.pull_request.number }}/
+
+      - name: Check that the report has been deleted
+        run: |
+          set +e
+
+          gcloud_output=$(gcloud storage ls --recursive gs://blazing-fire-playwright-reports/pr-${{ github.event.pull_request.number }} 2>&1)
+          exit_code=$?
+
+          echo "$gcloud_output" | tee gcloud_out.txt
+
+          if grep -q "gs://" gcloud_out.txt; then
+              echo "File(s) have been found in the folder /pr-${{ github.event.pull_request.number }}"
+              exit_code=1
+          fi
+
+          if grep -q "One or more URLs matched no objects" gcloud_out.txt; then
+              echo "The report folder is not found, skipping error."
+              exit_code=0
+          fi
+
+          exit $exit_code
